[project]
name = "hyper-agent"
version = "0.1.0"
description = "A Python project using uv"
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
dependencies = [
    # Add your dependencies here
]
requires-python = ">=3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 88
target-version = "py38"